import { Content } from "content.slint";
import { Menu } from "menu.slint";
import { AudioMetadata, LyricLine } from "type.slint";

// 界面入口
export component App inherits Window {
    title: "本地音乐播放器";
    preferred-width: 480px;
    preferred-height: 600px;

    // 音乐文件列表
    in property <[AudioMetadata]> music-list;
    // 当前选中项索引
    in property <int> selected-index;
    // 当前播放状态
    in property <bool> is-playing;
    // 主体窗口的显示和隐藏
    in property <bool> content-visible: true;
    // 详情窗口的显示和隐藏
    in property <bool> info-visible: false;
    // 当前播放进度
    in property <float> playback-progress;
    // 歌词数据
    in property <[LyricLine]> lyric-lines;
    // 当前播放行
    in property <int> current-line-index;
    // 音乐信息
    in property <AudioMetadata> audio-file;
    // 列表循环播放
    in property <bool> repeat-list: false;
    // 列表乱序播放
    in property <bool> shuffle-list: false;

    // 选择文件夹导入音乐
    callback find-music-files();
    // 播放歌曲
    callback playback-item(int);
    // 播放
    callback pressed-play(int);
    // 暂停
    callback pressed-pause(int);
    // 下一首
    callback pressed-next(int);
    // 上一首
    callback pressed-prev(int);
    // 列表重复
    callback pressed-repeat-list(int);
    // 乱序播放
    callback pressed-shuffle-list(int);

    // 主界面窗口
    VerticalLayout {
        spacing: 5px;
        Menu {
            height: 5%;
            new-requested => {
                root.find-music-files()
            }
        }

        Content {
            height: 95%;
            music-list: root.music-list;
            selected-index: root.selected-index;
            content-visible: root.content-visible;
            info-visible: root.info-visible;
            is-playing: root.is-playing;
            playback-progress: root.playback-progress;
            lyric-lines: root.lyric-lines;
            current-line-index: root.current-line-index;
            audio-file: root.audio-file;
            repeat-list: root.repeat-list;
            shuffle-list: root.shuffle-list;
            selected-item(idx) => {
                root.playback-item(idx)
            }
            pressed-play(idx) => {
                root.pressed-play(idx)
            }
            pressed-pause(idx) => {
                root.pressed-pause(idx)
            }
            pressed-next(idx) => {
                root.pressed-next(idx)
            }
            pressed-prev(idx) => {
                root.pressed-prev(idx)
            }
            pressed-repeat-list(idx) => {
                root.pressed-repeat-list(idx)
            }
            pressed-shuffle-list(idx) => {
                root.pressed-shuffle-list(idx)
            }
        }
    }
}
