import { ItemTitleInfo, MusicInfo, LyricInfo } from "type.slint";

// 管理程序主要变量, 避免从子组件中一直往上传递过多的属性和回调等信息
export global Attribute {
    // 全局样式属性
    // 系统字体指定, 针对 Mac Inter x86_64 平台默认的 slint 渲染引擎无法读取到中文字体的问题, 由后端根据平台特性制定字体
    // 不要去打包字体, 字体文件一般都是超过 10m 比较大, 开发时针对字体预览问题需手动指定默认值, 比如 冬青黑体 Hiragino Sans GB
    in property <string> default-font-family: "";
    // 字体加粗
    in property <int> default-font-weight: 800;
    // 字体颜色
    in property <brush> default-font-color: blue;

    // 窗口顶部标题, 歌曲播放时为 歌曲名-作者-专辑
    in property <string> top-title: @tr("Local Music Player");

    // 歌曲列表标题配置
    in property <[ItemTitleInfo]> item-title-info-list:[
        { text:@tr("歌名"), width: 40%},     
        { text:@tr("演唱"), width: 20%},     
        { text:@tr("专辑"), width: 30%},     
        { text:@tr("时长"), width: 10%},     
    ];

    // 歌曲列表
    in-out property <[MusicInfo]> music-list: [];

    // 歌曲播放进度条
    in property <float> progress;

    // 当前是否播放歌曲
    in property <bool> playing: true;

    // 当前歌曲
    in property <MusicInfo> current-music-info;

    // 当前封面图片
    in property <image> current-cover-image;

    // 当前歌词
    in property <[LyricInfo]> current-lyric-info-list: [];
    // 当前播放歌词行
    in property <int> current-lyric-index;

    // 选择音乐播放文件或者文件夹
    in property <string> music-folder: "";

    // 重复播放
    in property <bool> is-repeat-play;

    // 乱序播放
    in property <bool> is-shuffle-play;
}

// 全局单例公共工具函数
export global Util {
    // 格式化函数：秒 -> MM:SS
    public pure function format-time(seconds: float) -> string {
        let m = Math.floor(seconds / 60);
        let s = Math.floor(Math.mod(seconds, 60));
        return (m < 10 ? "0" : "") + m + ":" + (s < 10 ? "0" : "") + s;
    }
}
