import { LyricLine, AudioMetadata } from "type.slint";
import {
    ScrollView,
    ListView,
    ProgressIndicator,
    HorizontalBox,
} from "std-widgets.slint";

// 歌曲详情
export component Info {
    // 歌词数据
    in property <[LyricLine]> lyric-lines;
    // 当前播放行
    in property <int> current-line-index;
    // 音乐信息
    in property <AudioMetadata> file;
    // 歌曲播放状态
    in property <bool> is-playing;
    // 当前播放进度
    in property <float> playback-progress;
    // 列表循环播放
    in property <bool> repeat-list: false;
    // 列表乱序播放
    in property <bool> shuffle-list: false;

    // 播放
    callback pressed-play(int);
    // 暂停
    callback pressed-pause(int);
    // 下一首
    callback pressed-next(int);
    // 上一首
    callback pressed-prev(int);
    // 列表重复
    callback pressed-repeat-list(int);
    // 乱序播放
    callback pressed-shuffle-list(int);

    VerticalLayout {
        spacing: 5px;

        // 歌曲封面和歌词列表
        Rectangle {
            height: 65%;
            clip: true;
            Image {
                width: 100%;
                height: 100%;
                source: @image-url("/home/zhangguangxun/Desktop/th.jpeg");

                ListView {
                    for line[idx] in lyric-lines: Rectangle {
                        height: 25px;
                        width: 100%;

                        // 当前播放的歌词高亮
                        Text {
                            width: 100%;
                            text: line.text;
                            color: root.current-line-index == idx ? blue : black;
                            font-size: root.current-line-index == idx ? 20px : 15px;
                            horizontal-alignment: center;
                        }
                    }
                }
            }
        }

        // 歌曲播放进度条
        Rectangle {
            height: 10%;
            HorizontalLayout {
                alignment: space-between;
                Rectangle {
                    width: 10%;
                    Text {
                        width: 100%;
                        horizontal-alignment: center;
                        text: "-02:10";
                    }
                }

                Rectangle {
                    width: 80%;
                    ProgressIndicator {
                        width: 100%;
                        height: 10px;
                        progress: 0.34;
                    }
                }

                Rectangle {
                    width: 10%;
                    Text {
                        width: 100%;
                        horizontal-alignment: center;
                        text: file.duration-desc;
                    }
                }
            }
        }

        // 歌曲信息
        Rectangle {
            height: 10%;
            Text {
                width: 100%;
                horizontal-alignment: center;
                color: blue;
                font-weight: 600;
                text: file.title + " - " + file.artist + " - " + file.album;
            }
        }

        // 操作区域上一首下一首顺序播放乱序播放
        Rectangle {
            height: 10%;
            HorizontalLayout {
                width: 100%;
                Rectangle {
                    width: 20%;
                    Image {
                        source: @image-url("icons/shuffle-solid-full.svg");
                        width: 40px;
                        height: 40px;
                    }

                    TouchArea {
                        clicked => {
                            pressed-shuffle-list(file.index)
                        }
                    }
                }

                Rectangle {
                    width: 20%;
                    Image {
                        source: @image-url("icons/backward-solid-full.svg");
                        height: 40px;
                        width: 40px;
                    }

                    TouchArea {
                        clicked => {
                            pressed-next(file.index)
                        }
                    }
                }

                Rectangle {
                    width: 20%;
                    Image {
                        source: root.is-playing ? @image-url("icons/play-solid-full.svg") : @image-url("icons/pause-solid-full.svg");
                        height: 60px;
                        width: 60px;
                    }

                    TouchArea {
                        clicked => {
                            root.is-playing ? pressed-pause(file.index) : pressed-play(file.index);
                        }
                    }
                }

                Rectangle {
                    width: 20%;
                    Image {
                        source: @image-url("icons/forward-solid-full.svg");
                        height: 40px;
                        width: 40px;
                    }

                    TouchArea {
                        clicked => {
                            pressed-next(file.index)
                        }
                    }
                }

                Rectangle {
                    width: 20%;
                    Image {
                        source: @image-url("icons/repeat-solid-full.svg");
                        height: 40px;
                        width: 40px;
                    }

                    TouchArea {
                        clicked => {
                            pressed-repeat-list(file.index)
                        }
                    }
                }
            }
        }
    }
}
