import { ItemTitle } from "item-title.slint";
import { ItemContent } from "item-content.slint";
import { ItemPanel } from "item-panel.slint";
import { MusicInfo } from "type.slint";

// 歌曲列表主界面
export component Items inherits Window {
    // 双击播放歌曲
    callback playback(MusicInfo);
    // 乱序播放
    callback hope-shuffle-play(bool);
    // 上一首播放
    callback play-prev();
    // 下一首播放
    callback play-next();
    // 列表重复播放
    callback hope-repeat-play(bool);
    // 当前播放
    callback current-play();
    // 当前暂停
    callback current-pause();
    // 改变歌曲播放进度
    callback change-progress(float);

    VerticalLayout {
        // 歌曲标题
        ItemTitle {
            width: 100%;
            height: 5%;
        }
        // 歌曲列表
        ItemContent {
            width: 100%;
            height: 75%;
            playback(music-info) => {
                root.playback(music-info);
            }
        }
        // 播放控制区
        ItemPanel {
            width: 100%;
            height: 20%;

            hope-shuffle-play(mode-info) => {
                root.hope-shuffle-play(mode-info);
            }

            play-prev => {
                root.play-prev();
            }

            play-next => {
                root.play-next();
            }

            hope-repeat-play(mode-info) => {
                root.hope-repeat-play(mode-info);
            }

            current-play => {
                root.current-play();
            }

            current-pause => {
                root.current-pause();
            }

            change-progress(val) => {
                root.change-progress(val);
            }
        }
    }
}
