import { ListView } from "std-widgets.slint";
import { Attribute } from "global.slint";
import { ItemPanel } from "item-panel.slint";

// 歌词展示
export component Lyric inherits Window {
    // 乱序播放
    callback hope-shuffle-play(bool);
    // 上一首播放
    callback play-prev();
    // 下一首播放
    callback play-next();
    // 列表重复播放
    callback hope-repeat-play(bool);
    // 当前播放
    callback current-play();
    // 当前暂停
    callback current-pause();
    // 改变歌曲播放进度
    callback change-progress(float);

    VerticalLayout {
        Rectangle {
            width: 100%;
            height: 80%;
            VerticalLayout {
                padding: 10px;
                ListView {
                    for lyric-info[idx] in Attribute.current-lyric-info-list: Rectangle {
                        width: 100%;
                        height: 20px;
                        Text {
                            color: idx == Attribute.current-lyric-index ? blue : green;
                            font-size: idx == Attribute.current-lyric-index ? 16px : 12px;
                            text: lyric-info.text;
                        }
                    }
                }
            }
        }

        ItemPanel {
            width: 100%;
            height: 20%;

            hope-shuffle-play(mode-info) => {
                root.hope-shuffle-play(mode-info);
            }

            play-prev => {
                root.play-prev();
            }

            play-next => {
                root.play-next();
            }

            hope-repeat-play(mode-info) => {
                root.hope-repeat-play(mode-info);
            }

            current-play => {
                root.current-play();
            }

            current-pause => {
                root.current-pause();
            }

            change-progress(val) => {
                root.change-progress(val);
            }
        }
    }
}
